module Examples.Github.Scopes where

data Scope__AbortQueuedMigrationsPayload

data Scope__AcceptEnterpriseAdministratorInvitationPayload

data Scope__AcceptTopicSuggestionPayload

data Scope__ActorLocation

data Scope__AddAssigneesToAssignablePayload

data Scope__AddCommentPayload

data Scope__AddDiscussionCommentPayload

data Scope__AddEnterpriseSupportEntitlementPayload

data Scope__AddLabelsToLabelablePayload

data Scope__AddProjectCardPayload

data Scope__AddProjectColumnPayload

data Scope__AddProjectNextItemPayload

data Scope__AddPullRequestReviewCommentPayload

data Scope__AddPullRequestReviewPayload

data Scope__AddPullRequestReviewThreadPayload

data Scope__AddReactionPayload

data Scope__AddStarPayload

data Scope__AddUpvotePayload

data Scope__AddVerifiableDomainPayload

data Scope__AddedToProjectEvent

data Scope__App

data Scope__ApproveDeploymentsPayload

data Scope__ApproveVerifiableDomainPayload

data Scope__ArchiveRepositoryPayload

data Scope__AssignedEvent

data Scope__AutoMergeDisabledEvent

data Scope__AutoMergeEnabledEvent

data Scope__AutoMergeRequest

data Scope__AutoRebaseEnabledEvent

data Scope__AutoSquashEnabledEvent

data Scope__AutomaticBaseChangeFailedEvent

data Scope__AutomaticBaseChangeSucceededEvent

data Scope__BaseRefChangedEvent

data Scope__BaseRefDeletedEvent

data Scope__BaseRefForcePushedEvent

data Scope__Blame

data Scope__BlameRange

data Scope__Blob

data Scope__Bot

data Scope__BranchProtectionRule

data Scope__BranchProtectionRuleConflict

data Scope__BranchProtectionRuleConflictConnection

data Scope__BranchProtectionRuleConflictEdge

data Scope__BranchProtectionRuleConnection

data Scope__BranchProtectionRuleEdge

data Scope__BypassForcePushAllowance

data Scope__BypassForcePushAllowanceConnection

data Scope__BypassForcePushAllowanceEdge

data Scope__BypassPullRequestAllowance

data Scope__BypassPullRequestAllowanceConnection

data Scope__BypassPullRequestAllowanceEdge

data Scope__CancelEnterpriseAdminInvitationPayload

data Scope__CancelSponsorshipPayload

data Scope__ChangeUserStatusPayload

data Scope__CheckAnnotation

data Scope__CheckAnnotationConnection

data Scope__CheckAnnotationEdge

data Scope__CheckAnnotationPosition

data Scope__CheckAnnotationSpan

data Scope__CheckRun

data Scope__CheckRunConnection

data Scope__CheckRunEdge

data Scope__CheckStep

data Scope__CheckStepConnection

data Scope__CheckStepEdge

data Scope__CheckSuite

data Scope__CheckSuiteConnection

data Scope__CheckSuiteEdge

data Scope__ClearLabelsFromLabelablePayload

data Scope__CloneProjectPayload

data Scope__CloneTemplateRepositoryPayload

data Scope__CloseIssuePayload

data Scope__ClosePullRequestPayload

data Scope__ClosedEvent

data Scope__CodeOfConduct

data Scope__CommentDeletedEvent

data Scope__Commit

data Scope__CommitComment

data Scope__CommitCommentConnection

data Scope__CommitCommentEdge

data Scope__CommitCommentThread

data Scope__CommitConnection

data Scope__CommitContributionsByRepository

data Scope__CommitEdge

data Scope__CommitHistoryConnection

data Scope__ConnectedEvent

data Scope__ContributionCalendar

data Scope__ContributionCalendarDay

data Scope__ContributionCalendarMonth

data Scope__ContributionCalendarWeek

data Scope__ContributionsCollection

data Scope__ConvertProjectCardNoteToIssuePayload

data Scope__ConvertPullRequestToDraftPayload

data Scope__ConvertToDraftEvent

data Scope__ConvertedNoteToIssueEvent

data Scope__ConvertedToDiscussionEvent

data Scope__CreateBranchProtectionRulePayload

data Scope__CreateCheckRunPayload

data Scope__CreateCheckSuitePayload

data Scope__CreateCommitOnBranchPayload

data Scope__CreateDiscussionPayload

data Scope__CreateEnterpriseOrganizationPayload

data Scope__CreateEnvironmentPayload

data Scope__CreateIpAllowListEntryPayload

data Scope__CreateIssuePayload

data Scope__CreateMigrationSourcePayload

data Scope__CreateProjectPayload

data Scope__CreatePullRequestPayload

data Scope__CreateRefPayload

data Scope__CreateRepositoryPayload

data Scope__CreateSponsorshipPayload

data Scope__CreateTeamDiscussionCommentPayload

data Scope__CreateTeamDiscussionPayload

data Scope__CreatedCommitContribution

data Scope__CreatedCommitContributionConnection

data Scope__CreatedCommitContributionEdge

data Scope__CreatedIssueContribution

data Scope__CreatedIssueContributionConnection

data Scope__CreatedIssueContributionEdge

data Scope__CreatedPullRequestContribution

data Scope__CreatedPullRequestContributionConnection

data Scope__CreatedPullRequestContributionEdge

data Scope__CreatedPullRequestReviewContribution

data Scope__CreatedPullRequestReviewContributionConnection

data Scope__CreatedPullRequestReviewContributionEdge

data Scope__CreatedRepositoryContribution

data Scope__CreatedRepositoryContributionConnection

data Scope__CreatedRepositoryContributionEdge

data Scope__CrossReferencedEvent

data Scope__Cvss

data Scope__Cwe

data Scope__CweConnection

data Scope__CweEdge

data Scope__DeclineTopicSuggestionPayload

data Scope__DeleteBranchProtectionRulePayload

data Scope__DeleteDeploymentPayload

data Scope__DeleteDiscussionCommentPayload

data Scope__DeleteDiscussionPayload

data Scope__DeleteEnvironmentPayload

data Scope__DeleteIpAllowListEntryPayload

data Scope__DeleteIssueCommentPayload

data Scope__DeleteIssuePayload

data Scope__DeleteProjectCardPayload

data Scope__DeleteProjectColumnPayload

data Scope__DeleteProjectNextItemPayload

data Scope__DeleteProjectPayload

data Scope__DeletePullRequestReviewCommentPayload

data Scope__DeletePullRequestReviewPayload

data Scope__DeleteRefPayload

data Scope__DeleteTeamDiscussionCommentPayload

data Scope__DeleteTeamDiscussionPayload

data Scope__DeleteVerifiableDomainPayload

data Scope__DemilestonedEvent

data Scope__DeployKey

data Scope__DeployKeyConnection

data Scope__DeployKeyEdge

data Scope__DeployedEvent

data Scope__Deployment

data Scope__DeploymentConnection

data Scope__DeploymentEdge

data Scope__DeploymentEnvironmentChangedEvent

data Scope__DeploymentProtectionRule

data Scope__DeploymentProtectionRuleConnection

data Scope__DeploymentProtectionRuleEdge

data Scope__DeploymentRequest

data Scope__DeploymentRequestConnection

data Scope__DeploymentRequestEdge

data Scope__DeploymentReview

data Scope__DeploymentReviewConnection

data Scope__DeploymentReviewEdge

data Scope__DeploymentReviewerConnection

data Scope__DeploymentReviewerEdge

data Scope__DeploymentStatus

data Scope__DeploymentStatusConnection

data Scope__DeploymentStatusEdge

data Scope__DisablePullRequestAutoMergePayload

data Scope__DisconnectedEvent

data Scope__Discussion

data Scope__DiscussionCategory

data Scope__DiscussionCategoryConnection

data Scope__DiscussionCategoryEdge

data Scope__DiscussionComment

data Scope__DiscussionCommentConnection

data Scope__DiscussionCommentEdge

data Scope__DiscussionConnection

data Scope__DiscussionEdge

data Scope__DismissPullRequestReviewPayload

data Scope__DismissRepositoryVulnerabilityAlertPayload

data Scope__EnablePullRequestAutoMergePayload

data Scope__Enterprise

data Scope__EnterpriseAdministratorConnection

data Scope__EnterpriseAdministratorEdge

data Scope__EnterpriseAdministratorInvitation

data Scope__EnterpriseAdministratorInvitationConnection

data Scope__EnterpriseAdministratorInvitationEdge

data Scope__EnterpriseBillingInfo

data Scope__EnterpriseIdentityProvider

data Scope__EnterpriseMemberConnection

data Scope__EnterpriseMemberEdge

data Scope__EnterpriseOrganizationMembershipConnection

data Scope__EnterpriseOrganizationMembershipEdge

data Scope__EnterpriseOutsideCollaboratorConnection

data Scope__EnterpriseOutsideCollaboratorEdge

data Scope__EnterpriseOwnerInfo

data Scope__EnterprisePendingCollaboratorConnection

data Scope__EnterprisePendingCollaboratorEdge

data Scope__EnterprisePendingMemberInvitationConnection

data Scope__EnterprisePendingMemberInvitationEdge

data Scope__EnterpriseRepositoryInfo

data Scope__EnterpriseRepositoryInfoConnection

data Scope__EnterpriseRepositoryInfoEdge

data Scope__EnterpriseServerInstallation

data Scope__EnterpriseServerInstallationConnection

data Scope__EnterpriseServerInstallationEdge

data Scope__EnterpriseServerUserAccount

data Scope__EnterpriseServerUserAccountConnection

data Scope__EnterpriseServerUserAccountEdge

data Scope__EnterpriseServerUserAccountEmail

data Scope__EnterpriseServerUserAccountEmailConnection

data Scope__EnterpriseServerUserAccountEmailEdge

data Scope__EnterpriseServerUserAccountsUpload

data Scope__EnterpriseServerUserAccountsUploadConnection

data Scope__EnterpriseServerUserAccountsUploadEdge

data Scope__EnterpriseUserAccount

data Scope__EnterpriseUserAccountConnection

data Scope__EnterpriseUserAccountEdge

data Scope__Environment

data Scope__EnvironmentConnection

data Scope__EnvironmentEdge

data Scope__ExternalIdentity

data Scope__ExternalIdentityConnection

data Scope__ExternalIdentityEdge

data Scope__ExternalIdentitySamlAttributes

data Scope__ExternalIdentityScimAttributes

data Scope__FollowUserPayload

data Scope__FollowerConnection

data Scope__FollowingConnection

data Scope__FundingLink

data Scope__GenericHovercardContext

data Scope__Gist

data Scope__GistComment

data Scope__GistCommentConnection

data Scope__GistCommentEdge

data Scope__GistConnection

data Scope__GistEdge

data Scope__GistFile

data Scope__GitActor

data Scope__GitActorConnection

data Scope__GitActorEdge

data Scope__GitHubMetadata

data Scope__GpgSignature

data Scope__GrantEnterpriseOrganizationsMigratorRolePayload

data Scope__GrantMigratorRolePayload

data Scope__HeadRefDeletedEvent

data Scope__HeadRefForcePushedEvent

data Scope__HeadRefRestoredEvent

data Scope__Hovercard

data Scope__Import

data Scope__InviteEnterpriseAdminPayload

data Scope__IpAllowListEntry

data Scope__IpAllowListEntryConnection

data Scope__IpAllowListEntryEdge

data Scope__Issue

data Scope__IssueComment

data Scope__IssueCommentConnection

data Scope__IssueCommentEdge

data Scope__IssueConnection

data Scope__IssueContributionsByRepository

data Scope__IssueEdge

data Scope__IssueTemplate

data Scope__IssueTimelineConnection

data Scope__IssueTimelineItemEdge

data Scope__IssueTimelineItemsConnection

data Scope__IssueTimelineItemsEdge

data Scope__JoinedGitHubContribution

data Scope__Label

data Scope__LabelConnection

data Scope__LabelEdge

data Scope__LabeledEvent

data Scope__Language

data Scope__LanguageConnection

data Scope__LanguageEdge

data Scope__License

data Scope__LicenseRule

data Scope__LinkRepositoryToProjectPayload

data Scope__LockLockablePayload

data Scope__LockedEvent

data Scope__Mannequin

data Scope__MarkDiscussionCommentAsAnswerPayload

data Scope__MarkFileAsViewedPayload

data Scope__MarkPullRequestReadyForReviewPayload

data Scope__MarkedAsDuplicateEvent

data Scope__MarketplaceCategory

data Scope__MarketplaceListing

data Scope__MarketplaceListingConnection

data Scope__MarketplaceListingEdge

data Scope__MembersCanDeleteReposClearAuditEntry

data Scope__MembersCanDeleteReposDisableAuditEntry

data Scope__MembersCanDeleteReposEnableAuditEntry

data Scope__MentionedEvent

data Scope__MergeBranchPayload

data Scope__MergePullRequestPayload

data Scope__MergedEvent

data Scope__MigrationSource

data Scope__Milestone

data Scope__MilestoneConnection

data Scope__MilestoneEdge

data Scope__MilestonedEvent

data Scope__MinimizeCommentPayload

data Scope__MoveProjectCardPayload

data Scope__MoveProjectColumnPayload

data Scope__MovedColumnsInProjectEvent

data Scope__OauthApplicationCreateAuditEntry

data Scope__OidcProvider

data Scope__OrgAddBillingManagerAuditEntry

data Scope__OrgAddMemberAuditEntry

data Scope__OrgBlockUserAuditEntry

data Scope__OrgConfigDisableCollaboratorsOnlyAuditEntry

data Scope__OrgConfigEnableCollaboratorsOnlyAuditEntry

data Scope__OrgCreateAuditEntry

data Scope__OrgDisableOauthAppRestrictionsAuditEntry

data Scope__OrgDisableSamlAuditEntry

data Scope__OrgDisableTwoFactorRequirementAuditEntry

data Scope__OrgEnableOauthAppRestrictionsAuditEntry

data Scope__OrgEnableSamlAuditEntry

data Scope__OrgEnableTwoFactorRequirementAuditEntry

data Scope__OrgInviteMemberAuditEntry

data Scope__OrgInviteToBusinessAuditEntry

data Scope__OrgOauthAppAccessApprovedAuditEntry

data Scope__OrgOauthAppAccessDeniedAuditEntry

data Scope__OrgOauthAppAccessRequestedAuditEntry

data Scope__OrgRemoveBillingManagerAuditEntry

data Scope__OrgRemoveMemberAuditEntry

data Scope__OrgRemoveOutsideCollaboratorAuditEntry

data Scope__OrgRestoreMemberAuditEntry

data Scope__OrgRestoreMemberMembershipOrganizationAuditEntryData

data Scope__OrgRestoreMemberMembershipRepositoryAuditEntryData

data Scope__OrgRestoreMemberMembershipTeamAuditEntryData

data Scope__OrgUnblockUserAuditEntry

data Scope__OrgUpdateDefaultRepositoryPermissionAuditEntry

data Scope__OrgUpdateMemberAuditEntry

data Scope__OrgUpdateMemberRepositoryCreationPermissionAuditEntry

data Scope__OrgUpdateMemberRepositoryInvitationPermissionAuditEntry

data Scope__Organization

data Scope__OrganizationAuditEntryConnection

data Scope__OrganizationAuditEntryEdge

data Scope__OrganizationConnection

data Scope__OrganizationEdge

data Scope__OrganizationEnterpriseOwnerConnection

data Scope__OrganizationEnterpriseOwnerEdge

data Scope__OrganizationIdentityProvider

data Scope__OrganizationInvitation

data Scope__OrganizationInvitationConnection

data Scope__OrganizationInvitationEdge

data Scope__OrganizationMemberConnection

data Scope__OrganizationMemberEdge

data Scope__OrganizationTeamsHovercardContext

data Scope__OrganizationsHovercardContext

data Scope__Package

data Scope__PackageConnection

data Scope__PackageEdge

data Scope__PackageFile

data Scope__PackageFileConnection

data Scope__PackageFileEdge

data Scope__PackageStatistics

data Scope__PackageTag

data Scope__PackageVersion

data Scope__PackageVersionConnection

data Scope__PackageVersionEdge

data Scope__PackageVersionStatistics

data Scope__PageInfo

data Scope__PermissionSource

data Scope__PinIssuePayload

data Scope__PinnableItemConnection

data Scope__PinnableItemEdge

data Scope__PinnedDiscussion

data Scope__PinnedDiscussionConnection

data Scope__PinnedDiscussionEdge

data Scope__PinnedEvent

data Scope__PinnedIssue

data Scope__PinnedIssueConnection

data Scope__PinnedIssueEdge

data Scope__PrivateRepositoryForkingDisableAuditEntry

data Scope__PrivateRepositoryForkingEnableAuditEntry

data Scope__ProfileItemShowcase

data Scope__Project

data Scope__ProjectCard

data Scope__ProjectCardConnection

data Scope__ProjectCardEdge

data Scope__ProjectColumn

data Scope__ProjectColumnConnection

data Scope__ProjectColumnEdge

data Scope__ProjectConnection

data Scope__ProjectEdge

data Scope__ProjectNext

data Scope__ProjectNextConnection

data Scope__ProjectNextEdge

data Scope__ProjectNextField

data Scope__ProjectNextFieldConnection

data Scope__ProjectNextFieldEdge

data Scope__ProjectNextItem

data Scope__ProjectNextItemConnection

data Scope__ProjectNextItemEdge

data Scope__ProjectNextItemFieldValue

data Scope__ProjectNextItemFieldValueConnection

data Scope__ProjectNextItemFieldValueEdge

data Scope__ProjectProgress

data Scope__PublicKey

data Scope__PublicKeyConnection

data Scope__PublicKeyEdge

data Scope__PullRequest

data Scope__PullRequestChangedFile

data Scope__PullRequestChangedFileConnection

data Scope__PullRequestChangedFileEdge

data Scope__PullRequestCommit

data Scope__PullRequestCommitCommentThread

data Scope__PullRequestCommitConnection

data Scope__PullRequestCommitEdge

data Scope__PullRequestConnection

data Scope__PullRequestContributionsByRepository

data Scope__PullRequestEdge

data Scope__PullRequestReview

data Scope__PullRequestReviewComment

data Scope__PullRequestReviewCommentConnection

data Scope__PullRequestReviewCommentEdge

data Scope__PullRequestReviewConnection

data Scope__PullRequestReviewContributionsByRepository

data Scope__PullRequestReviewEdge

data Scope__PullRequestReviewThread

data Scope__PullRequestReviewThreadConnection

data Scope__PullRequestReviewThreadEdge

data Scope__PullRequestRevisionMarker

data Scope__PullRequestTemplate

data Scope__PullRequestTimelineConnection

data Scope__PullRequestTimelineItemEdge

data Scope__PullRequestTimelineItemsConnection

data Scope__PullRequestTimelineItemsEdge

data Scope__Push

data Scope__PushAllowance

data Scope__PushAllowanceConnection

data Scope__PushAllowanceEdge

data Scope__RateLimit

data Scope__ReactingUserConnection

data Scope__ReactingUserEdge

data Scope__Reaction

data Scope__ReactionConnection

data Scope__ReactionEdge

data Scope__ReactionGroup

data Scope__ReactorConnection

data Scope__ReactorEdge

data Scope__ReadyForReviewEvent

data Scope__Ref

data Scope__RefConnection

data Scope__RefEdge

data Scope__RefUpdateRule

data Scope__ReferencedEvent

data Scope__RegenerateEnterpriseIdentityProviderRecoveryCodesPayload

data Scope__RegenerateVerifiableDomainTokenPayload

data Scope__RejectDeploymentsPayload

data Scope__Release

data Scope__ReleaseAsset

data Scope__ReleaseAssetConnection

data Scope__ReleaseAssetEdge

data Scope__ReleaseConnection

data Scope__ReleaseEdge

data Scope__RemoveAssigneesFromAssignablePayload

data Scope__RemoveEnterpriseAdminPayload

data Scope__RemoveEnterpriseIdentityProviderPayload

data Scope__RemoveEnterpriseOrganizationPayload

data Scope__RemoveEnterpriseSupportEntitlementPayload

data Scope__RemoveLabelsFromLabelablePayload

data Scope__RemoveOutsideCollaboratorPayload

data Scope__RemoveReactionPayload

data Scope__RemoveStarPayload

data Scope__RemoveUpvotePayload

data Scope__RemovedFromProjectEvent

data Scope__RenamedTitleEvent

data Scope__ReopenIssuePayload

data Scope__ReopenPullRequestPayload

data Scope__ReopenedEvent

data Scope__RepoAccessAuditEntry

data Scope__RepoAddMemberAuditEntry

data Scope__RepoAddTopicAuditEntry

data Scope__RepoArchivedAuditEntry

data Scope__RepoChangeMergeSettingAuditEntry

data Scope__RepoConfigDisableAnonymousGitAccessAuditEntry

data Scope__RepoConfigDisableCollaboratorsOnlyAuditEntry

data Scope__RepoConfigDisableContributorsOnlyAuditEntry

data Scope__RepoConfigDisableSockpuppetDisallowedAuditEntry

data Scope__RepoConfigEnableAnonymousGitAccessAuditEntry

data Scope__RepoConfigEnableCollaboratorsOnlyAuditEntry

data Scope__RepoConfigEnableContributorsOnlyAuditEntry

data Scope__RepoConfigEnableSockpuppetDisallowedAuditEntry

data Scope__RepoConfigLockAnonymousGitAccessAuditEntry

data Scope__RepoConfigUnlockAnonymousGitAccessAuditEntry

data Scope__RepoCreateAuditEntry

data Scope__RepoDestroyAuditEntry

data Scope__RepoRemoveMemberAuditEntry

data Scope__RepoRemoveTopicAuditEntry

data Scope__Repository

data Scope__RepositoryCollaboratorConnection

data Scope__RepositoryCollaboratorEdge

data Scope__RepositoryConnection

data Scope__RepositoryContactLink

data Scope__RepositoryEdge

data Scope__RepositoryInteractionAbility

data Scope__RepositoryInvitation

data Scope__RepositoryInvitationConnection

data Scope__RepositoryInvitationEdge

data Scope__RepositoryMigration

data Scope__RepositoryMigrationConnection

data Scope__RepositoryMigrationEdge

data Scope__RepositoryTopic

data Scope__RepositoryTopicConnection

data Scope__RepositoryTopicEdge

data Scope__RepositoryVisibilityChangeDisableAuditEntry

data Scope__RepositoryVisibilityChangeEnableAuditEntry

data Scope__RepositoryVulnerabilityAlert

data Scope__RepositoryVulnerabilityAlertConnection

data Scope__RepositoryVulnerabilityAlertEdge

data Scope__RequestReviewsPayload

data Scope__RequiredStatusCheckDescription

data Scope__RerequestCheckSuitePayload

data Scope__ResolveReviewThreadPayload

data Scope__RestrictedContribution

data Scope__ReviewDismissalAllowance

data Scope__ReviewDismissalAllowanceConnection

data Scope__ReviewDismissalAllowanceEdge

data Scope__ReviewDismissedEvent

data Scope__ReviewRequest

data Scope__ReviewRequestConnection

data Scope__ReviewRequestEdge

data Scope__ReviewRequestRemovedEvent

data Scope__ReviewRequestedEvent

data Scope__ReviewStatusHovercardContext

data Scope__RevokeEnterpriseOrganizationsMigratorRolePayload

data Scope__RevokeMigratorRolePayload

data Scope__SavedReply

data Scope__SavedReplyConnection

data Scope__SavedReplyEdge

data Scope__SearchResultItemConnection

data Scope__SearchResultItemEdge

data Scope__SecurityAdvisory

data Scope__SecurityAdvisoryConnection

data Scope__SecurityAdvisoryEdge

data Scope__SecurityAdvisoryIdentifier

data Scope__SecurityAdvisoryPackage

data Scope__SecurityAdvisoryPackageVersion

data Scope__SecurityAdvisoryReference

data Scope__SecurityVulnerability

data Scope__SecurityVulnerabilityConnection

data Scope__SecurityVulnerabilityEdge

data Scope__SetEnterpriseIdentityProviderPayload

data Scope__SetOrganizationInteractionLimitPayload

data Scope__SetRepositoryInteractionLimitPayload

data Scope__SetUserInteractionLimitPayload

data Scope__SmimeSignature

data Scope__SponsorConnection

data Scope__SponsorEdge

data Scope__SponsorableItemConnection

data Scope__SponsorableItemEdge

data Scope__SponsorsActivity

data Scope__SponsorsActivityConnection

data Scope__SponsorsActivityEdge

data Scope__SponsorsGoal

data Scope__SponsorsListing

data Scope__SponsorsTier

data Scope__SponsorsTierAdminInfo

data Scope__SponsorsTierConnection

data Scope__SponsorsTierEdge

data Scope__Sponsorship

data Scope__SponsorshipConnection

data Scope__SponsorshipEdge

data Scope__SponsorshipNewsletter

data Scope__SponsorshipNewsletterConnection

data Scope__SponsorshipNewsletterEdge

data Scope__StargazerConnection

data Scope__StargazerEdge

data Scope__StarredRepositoryConnection

data Scope__StarredRepositoryEdge

data Scope__StartRepositoryMigrationPayload

data Scope__Status

data Scope__StatusCheckRollup

data Scope__StatusCheckRollupContextConnection

data Scope__StatusCheckRollupContextEdge

data Scope__StatusContext

data Scope__SubmitPullRequestReviewPayload

data Scope__Submodule

data Scope__SubmoduleConnection

data Scope__SubmoduleEdge

data Scope__SubscribedEvent

data Scope__SuggestedReviewer

data Scope__Tag

data Scope__Team

data Scope__TeamAddMemberAuditEntry

data Scope__TeamAddRepositoryAuditEntry

data Scope__TeamChangeParentTeamAuditEntry

data Scope__TeamConnection

data Scope__TeamDiscussion

data Scope__TeamDiscussionComment

data Scope__TeamDiscussionCommentConnection

data Scope__TeamDiscussionCommentEdge

data Scope__TeamDiscussionConnection

data Scope__TeamDiscussionEdge

data Scope__TeamEdge

data Scope__TeamMemberConnection

data Scope__TeamMemberEdge

data Scope__TeamRemoveMemberAuditEntry

data Scope__TeamRemoveRepositoryAuditEntry

data Scope__TeamRepositoryConnection

data Scope__TeamRepositoryEdge

data Scope__TextMatch

data Scope__TextMatchHighlight

data Scope__Topic

data Scope__TransferIssuePayload

data Scope__TransferredEvent

data Scope__Tree

data Scope__TreeEntry

data Scope__UnarchiveRepositoryPayload

data Scope__UnassignedEvent

data Scope__UnfollowUserPayload

data Scope__UnknownSignature

data Scope__UnlabeledEvent

data Scope__UnlinkRepositoryFromProjectPayload

data Scope__UnlockLockablePayload

data Scope__UnlockedEvent

data Scope__UnmarkDiscussionCommentAsAnswerPayload

data Scope__UnmarkFileAsViewedPayload

data Scope__UnmarkIssueAsDuplicatePayload

data Scope__UnmarkedAsDuplicateEvent

data Scope__UnminimizeCommentPayload

data Scope__UnpinIssuePayload

data Scope__UnpinnedEvent

data Scope__UnresolveReviewThreadPayload

data Scope__UnsubscribedEvent

data Scope__UpdateBranchProtectionRulePayload

data Scope__UpdateCheckRunPayload

data Scope__UpdateCheckSuitePreferencesPayload

data Scope__UpdateDiscussionCommentPayload

data Scope__UpdateDiscussionPayload

data Scope__UpdateEnterpriseAdministratorRolePayload

data Scope__UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload

data Scope__UpdateEnterpriseDefaultRepositoryPermissionSettingPayload

data Scope__UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload

data Scope__UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload

data Scope__UpdateEnterpriseMembersCanDeleteIssuesSettingPayload

data Scope__UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload

data Scope__UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload

data Scope__UpdateEnterpriseMembersCanMakePurchasesSettingPayload

data Scope__UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload

data Scope__UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload

data Scope__UpdateEnterpriseOrganizationProjectsSettingPayload

data Scope__UpdateEnterpriseOwnerOrganizationRolePayload

data Scope__UpdateEnterpriseProfilePayload

data Scope__UpdateEnterpriseRepositoryProjectsSettingPayload

data Scope__UpdateEnterpriseTeamDiscussionsSettingPayload

data Scope__UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload

data Scope__UpdateEnvironmentPayload

data Scope__UpdateIpAllowListEnabledSettingPayload

data Scope__UpdateIpAllowListEntryPayload

data Scope__UpdateIpAllowListForInstalledAppsEnabledSettingPayload

data Scope__UpdateIssueCommentPayload

data Scope__UpdateIssuePayload

data Scope__UpdateNotificationRestrictionSettingPayload

data Scope__UpdateOrganizationAllowPrivateRepositoryForkingSettingPayload

data Scope__UpdateProjectCardPayload

data Scope__UpdateProjectColumnPayload

data Scope__UpdateProjectNextItemFieldPayload

data Scope__UpdateProjectPayload

data Scope__UpdatePullRequestBranchPayload

data Scope__UpdatePullRequestPayload

data Scope__UpdatePullRequestReviewCommentPayload

data Scope__UpdatePullRequestReviewPayload

data Scope__UpdateRefPayload

data Scope__UpdateRepositoryPayload

data Scope__UpdateSponsorshipPreferencesPayload

data Scope__UpdateSubscriptionPayload

data Scope__UpdateTeamDiscussionCommentPayload

data Scope__UpdateTeamDiscussionPayload

data Scope__UpdateTopicsPayload

data Scope__User

data Scope__UserBlockedEvent

data Scope__UserConnection

data Scope__UserContentEdit

data Scope__UserContentEditConnection

data Scope__UserContentEditEdge

data Scope__UserEdge

data Scope__UserEmailMetadata

data Scope__UserStatus

data Scope__UserStatusConnection

data Scope__UserStatusEdge

data Scope__VerifiableDomain

data Scope__VerifiableDomainConnection

data Scope__VerifiableDomainEdge

data Scope__VerifyVerifiableDomainPayload

data Scope__ViewerHovercardContext

data Scope__Workflow

data Scope__WorkflowRun

data Scope__Actor

data Scope__Assignable

data Scope__AuditEntry

data Scope__Closable

data Scope__Comment

data Scope__Contribution

data Scope__Deletable

data Scope__EnterpriseAuditEntryData

data Scope__GitObject

data Scope__GitSignature

data Scope__HovercardContext

data Scope__Labelable

data Scope__Lockable

data Scope__MemberStatusable

data Scope__Migration

data Scope__Minimizable

data Scope__Node

data Scope__OauthApplicationAuditEntryData

data Scope__OrganizationAuditEntryData

data Scope__PackageOwner

data Scope__ProfileOwner

data Scope__ProjectNextOwner

data Scope__ProjectOwner

data Scope__Reactable

data Scope__RepositoryAuditEntryData

data Scope__RepositoryDiscussionAuthor

data Scope__RepositoryDiscussionCommentAuthor

data Scope__RepositoryInfo

data Scope__RepositoryNode

data Scope__RepositoryOwner

data Scope__RequirableByPullRequest

data Scope__Sponsorable

data Scope__Starrable

data Scope__Subscribable

data Scope__TeamAuditEntryData

data Scope__TopicAuditEntryData

data Scope__UniformResourceLocatable

data Scope__Updatable

data Scope__UpdatableComment

data Scope__Votable

data Scope__Assignee

data Scope__AuditEntryActor

data Scope__BranchActorAllowanceActor

data Scope__Closer

data Scope__CreatedIssueOrRestrictedContribution

data Scope__CreatedPullRequestOrRestrictedContribution

data Scope__CreatedRepositoryOrRestrictedContribution

data Scope__DeploymentReviewer

data Scope__EnterpriseMember

data Scope__IpAllowListOwner

data Scope__IssueOrPullRequest

data Scope__IssueTimelineItem

data Scope__IssueTimelineItems

data Scope__MilestoneItem

data Scope__OrgRestoreMemberAuditEntryMembership

data Scope__OrganizationAuditEntry

data Scope__PermissionGranter

data Scope__PinnableItem

data Scope__ProjectCardItem

data Scope__ProjectNextItemContent

data Scope__PullRequestTimelineItem

data Scope__PullRequestTimelineItems

data Scope__PushAllowanceActor

data Scope__Reactor

data Scope__ReferencedSubject

data Scope__RenamedTitleSubject

data Scope__RequestedReviewer

data Scope__ReviewDismissalAllowanceActor

data Scope__SearchResultItem

data Scope__Sponsor

data Scope__SponsorableItem

data Scope__StatusCheckRollupContext

data Scope__VerifiableDomainOwner
