#!/usr/bin/env node

// make work with https://github.com/purescript-web/purescript-web-socket/blob/master/src/Web/Socket/WebSocket.js
global.WebSocket = require('ws')

// same is generated by `spago run ....` to `./.spago/run.js`
require('../output/Examples.MyTests.Main').main()
